### ISSUE TITLE
Add compiled binaries to new github releases

### ISSUE THREAD

**Issue by rfhold** [stablekernel/protoc-gen-go-mcp#59]
Make the action trigger based on new releases, we should be able to use the built in `secrets.GITHUB_TOKEN`. Github action has the matrix option for this.

Something like this paired with `GOOS` and `GOARCH`
```yaml
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
```
