### ISSUE TITLE
Setup CI/CD for the repo

### ISSUE THREAD

**Issue by erikist** [stablekernel/protoc-gen-go-mcp#6]
First step is to add the repo to the GitHub App installation
GitHub > Stable Kernel > Settings > GitHub Apps > StableKernelTokenBot > Select repositories > add protoc-gen-go-mcp
Then after we update [dev.yaml](https://github.com/stablekernel/github-token-bot/blob/main/dev.yaml) and add protoc-gen-go-mcp there, it should start providing tokens.
```
  - repository: protoc-gen-go-mcp
    secret: RELEASE_GH_TOKEN
    environment:
      name: release
      protection:
        enabled: true
    permissions:
      repositories:
        - protoc-gen-go-mcp
```
